### ISSUE TITLE
Redmine: Hook fails to update repository or issues

### ISSUE THREAD

**Issue by kostajh** [github/github-services#1051] opened 2015-05-12 18:07 UTC
I'm seeing two issues with the Redmine webservice hook on Redmine 3.0.2:

```
Started GET "/sys/fetch_changesets?id=savaslabs&key=REDACTED" for REDACTED at 2015-05-12 13:57:51 -0400
Processing by SysController#fetch_changesets as */*
  Parameters: {"id"=>"savaslabs", "key"=>"REDACTED"}
  Rendered text template (0.0ms)
Completed 200 OK in 8ms (Views: 0.4ms | ActiveRecord: 0.3ms)
```
I have a project, `savaslabs` in Redmine, with a repo that has an ID of `savaslabs-github-io`. My understanding is that `/sys/fetch_changesets` should get the latest commits from GitHub, but this doesn't work.

```
Started PUT "/issues/37.json?REDACTED
Processing by IssuesController#update as JSON
  Parameters: {"issue"=>{"notes"=>"  Commit: 12e86d0b3fdf14235eac9f2b507c38ea413fa2ac\n      https://github.com/savaslabs/savaslabs.github.io/commit/12e86d0b3fdf14235eac9f2b507c38ea413fa2ac\n  Author: Kosta Harlan <kosta@kostaharlan.net>\n  Date:   2015-05-12 (Tue, 12 May 2015)\n\n  Log Message:\n  -----------\n  Fixes #37\n"}, "id"=>"37"}
  Current user: anonymous
Filter chain halted as :check_if_login_required rendered or redirected
Completed 401 Unauthorized in 3ms (ActiveRecord: 0.3ms)
```

Are there any permissions that need to be granted to the `anonymous` user role? Am I missing something in the configuration on GitHub or Redmine?

Thanks in advance for any help.

**Comment by kdaigle** [comment] 2015-08-17 17:24
@kostajh has this been fixed via the work in https://github.com/koppen/redmine_github_hook/issues/73? With many of these services, it is hard to differentiate if the problem is in the GitHub service or with the integrated application. :smile:

**Comment by kostajh** [comment] 2015-08-19 12:53
@kdaigle yes, it seems to be working now.

**Comment by kdaigle** [comment] 2015-08-19 13:09
@kostajh glad to hear it! :smile:

**Closed** 2015-08-19 13:09 UTC
